# Generated by Django 5.2.10 on 2026-04-04 15:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Заголовок')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Описание')),
                ('ad_type', models.CharField(choices=[('sale', 'Продажа'), ('purchase', 'Покупка'), ('service', 'Услуги'), ('exchange', 'Обмен'), ('rent', 'Аренда')], default='sale', max_length=20, verbose_name='Тип объявления')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Телефон для связи')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для связи')),
                ('contact_name', models.CharField(default='Продавец', max_length=100, verbose_name='Имя контактного лица')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='ads/main/%Y/%m/', verbose_name='Главное изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published_until', models.DateTimeField(blank=True, null=True, verbose_name='Актуально до')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='board.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='board_ad_created_f59c7b_idx'), models.Index(fields=['category', '-created_at'], name='board_ad_categor_3cf706_idx'), models.Index(fields=['is_active'], name='board_ad_is_acti_46510c_idx')],
            },
        ),
    ]
