# Generated by Django 5.2.10 on 2026-04-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/img/%Y/%m/', verbose_name='Главное изображение'),
        ),
    ]
