# Generated by Django 5.2.10 on 2026-04-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_adfile_adimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adfile',
            name='title',
        ),
    ]
