# Generated by Django 5.2.10 on 2026-05-07 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_adfile_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adimage',
            name='unique_main_image_per_ad',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='adimage',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='adfile',
            name='file',
            field=models.FileField(help_text=('Поддерживаемые форматы: .PDF, .TXT, .DOC, .DOCX, .XLS, .XLSX, .ZIP, .RAR, MP4, WEBM, MOV',), upload_to='ads/files/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.pdf', '.txt', '.doc', '.docx', '.xls', '.xlsx', '.zip', '.rar', 'mp4', 'webm', 'mov'])], verbose_name='Файл'),
        ),
    ]
